#!/bin/sh

lb config noauto \
--clean \
--debug \
--cache-stages "bootstrap" \
--binary-images iso-hybrid \
--bootloaders "syslinux,grub-efi" \
--distribution "sid" \
--iso-volume "$(date +%Y-%m-%d)" \
--iso-application "Towel Live" \
--iso-publisher "Juergen Fiedler - juergen.fiedler@gmail.com" \
--iso-volume "towel-$(date +%m%d%Y)" \
--debian-installer "false" \
--binary-filesystem "fat32" \
--architectures "i386" \
--linux-flavours "686" \
--apt-recommends "false" \
--apt-secure "false" \
--apt-options "--yes " \
--security "false" \
--win32-loader false \
--initsystem "systemd" \
--parent-mirror-bootstrap http://ftp.us.debian.org/debian/ \
--mirror-bootstrap http://ftp.us.debian.org/debian/ \
--parent-mirror-binary http://ftp.us.debian.org/debian/ \
--memtest memtest86+ \
--bootappend-live "boot=live components quiet splash timezone=America/New_York" \
--bootappend-live-failsafe "boot=live components memtest noapic noapm nodma nomce nolapic nomodeset nosmp nosplash vga=normal nox11autologin timezone=America/New_York"

