#!/bin/sh

lb config noauto \
--clean \
--debug \
--cache-stages "bootstrap" \
--bootstrap "debootstrap" \
--binary-images iso-hybrid \
--bootloader "syslinux" \
--distribution "sid" \
--iso-volume "$(date +%Y-%m-%d)" \
--iso-application "Towel Live" \
--iso-publisher "Juergen Fiedler - juergen.fiedler@gmail.com" \
--iso-volume "towel-$(date +%m%d%Y)" \
--debian-installer "false" \
--binary-filesystem "fat32" \
--architectures "i386" \
--linux-flavours "486" \
--apt-recommends "false" \
--apt-secure "false" \
--apt-options "--yes --force-yes --auto-remove" \
--security "false" \
--win32-loader false \
--initsystem "sysvinit" \
--parent-mirror-bootstrap http://ftp.us.debian.org/debian/ \
--mirror-bootstrap http://ftp.us.debian.org/debian/ \
--parent-mirror-binary http://ftp.us.debian.org/debian/ \
--memtest memtest86
