#!/bin/sh
### BEGIN INIT INFO
# Provides:          customize
# Required-Start:
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

case "$1" in
  start)
        echo -n Running final customisations...
        /sbin/ldconfig
	touch /var/lib/misc/udhcpd.leases
	mkdir -p /mnt/tmp/
        ;;
  stop)
        exit 0
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop}" >&2
        exit 1
        ;;
esac

